Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,7 +19,7 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
-          python-version: '3.8'
+          python-version: "3.8"
 
       - name: Install backend dependencies
         run: |
@@ -53,3 +53,45 @@ jobs:
         run: |
           cd frontend
           npm test
+
+check-docker-compose:
+  needs: [setup-backend, setup-frontend]
+  runs-on: ubuntu-latest
+
+  steps:
+    - uses: actions/checkout@v2
+
+    - name: Set up Docker and Docker Compose
+      run: |
+      sudo rm /usr/local/bin/docker-compose
+      curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o docker-compose
+      chmod +x docker-compose
+      sudo mv docker-compose /usr/local/bin
+
+    - name: Build and run with Docker Compose
+      run: |
+      docker-compose up -d
+      RETRIES=30
+      SLEEP_DURATION=30
+      SUCCESS=false
+
+      echo "Waiting for the application to start and become available at localhost:4173..."
+      for ((i=0; i<RETRIES; i++)); do
+        if curl -f http://localhost:4173/; then
+        SUCCESS=true
+        break
+        fi
+        echo "Attempt $((i+1)) of $RETRIES failed, retrying in $SLEEP_DURATION seconds..."
+        sleep $SLEEP_DURATION
+      done
+
+      if [ "$SUCCESS" = true ]; then
+        echo "Successfully connected to the application on localhost:4173!"
+      else
+        echo "Failed to connect to the application on localhost:4173 after $RETRIES retries."
+        exit 1
+      fi
+
+    - name: Cleanup Docker Compose
+      run: |
+      docker-compose down
